import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Layout } from "@/components/Layout/Layout";
import { CustomThemeProvider } from "@/utils/CustomTheme";
import Head from "next/head";
export const App = ({ Component, pageProps }: AppProps) => {
  return (
    <CustomThemeProvider>
      <Layout>
        <Component {...pageProps} />
        <Head>
          <title>Food Delivery</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logo.svg" />
        </Head>
      </Layout>
    </CustomThemeProvider>
  );
};

export default App;
